name: publish-static-site
on: push
jobs: 
  publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      - run: ls
      - run: npm install
      - run: ls
      - run: npm run build
      - run: ls ./dist
      - run: git remote -v
      - run: cp CNAME ./dist/CNAME
      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
